
package com.example.webservices.logs.client.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogsServiceImplService", targetNamespace = "http://service.soap.example.com/", wsdlLocation = "http://localhost:8090/ws/logs?wsdl")
public class LogsServiceImplService
    extends Service
{

    private final static URL LOGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOGSSERVICEIMPLSERVICE_QNAME = new QName("http://service.soap.example.com/", "LogsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/ws/logs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOGSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LogsServiceImplService() {
        super(__getWsdlLocation(), LOGSSERVICEIMPLSERVICE_QNAME);
    }

    public LogsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGSSERVICEIMPLSERVICE_QNAME);
    }

    public LogsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogsService
     */
    @WebEndpoint(name = "LogsServicePort")
    public LogsService getLogsServicePort() {
        return super.getPort(new QName("http://service.soap.example.com/", "LogsServicePort"), LogsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogsService
     */
    @WebEndpoint(name = "LogsServicePort")
    public LogsService getLogsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.example.com/", "LogsServicePort"), LogsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOGSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
