
package com.example.webservices.logs.client.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RepException", targetNamespace = "http://service.SOAP/")
public class RepException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RepException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RepException_Exception(String message, RepException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RepException_Exception(String message, RepException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.webservices.logs.client.wsdl.RepException
     */
    public RepException getFaultInfo() {
        return faultInfo;
    }

}
